### ISSUE TITLE
Configure alliance proxy server for searching

### ISSUE THREAD

**Issue by thatbudakguy** [Alliance-PCJWG/alliance-newui-dev#1]
```
var PROXY_SERVER = 'http://your-server:your-port';
```
the line above in [gulp/config.js](https://github.com/Alliance-PCJWG/alliance-newui-dev/blob/master/gulp/config.js#L59) becomes:
```
var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com/';
```

**Comment by jeremymcwilliams** [comment]
here is my comment

**Comment by bkelm** [comment]
I have:

var PROXY_SERVER = 'https://alliance-primo.hosted.exlibrisgroup.com'
//var PROXY_SERVER = 'http://alliance-primo-sb.hosted.exlibrisgroup.com'
